# Generated by Django 5.2.17 on 2026-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_telno', models.CharField(blank=True, max_length=13, null=True)),
                ('customer_postalcode', models.CharField(blank=True, max_length=8, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=40, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('delete_flag', models.TextField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_numbering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('dept_id', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee2',
            fields=[
                ('employee_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=32, null=True)),
                ('boss_no', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'employee2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('pk', models.CompositePrimaryKey('order_no', 'item_code', blank=True, editable=False, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('order_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('detail_num', models.IntegerField(blank=True, null=True)),
                ('deliver_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('employee_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salary_details',
                'managed': False,
            },
        ),
    ]
