# Generated by Django 5.2.17 on 2026-10-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee2',
        ),
        migrations.DeleteModel(
            name='SalaryDetails',
        ),
    ]
